## IMI configuration file
## Documentation @ https://imi.readthedocs.io/en/latest/getting-started/imi-config-file.html

## General
<<<<<<< HEAD
RunName: "NY_2018_3MONTH"
=======
RunName: "NY_2018"
isAWS: false
>>>>>>> d9df655488eab9901ca902dbcca56e455b1812e0
UseSlurm: true
SafeMode: false
S3Upload: false

## Period of interest
<<<<<<< HEAD
StartDate: 20180501
EndDate: 20180801
SpinupMonths: 1

## Use blended TROPOMI+GOSAT data (true)? Or use operational TROPOMI data (false)?
BlendedTROPOMI: false

## Use observations over water? Set to false to filter out water observations
UseWaterObs: false
=======
StartDate: 20180101
EndDate: 20181201
SpinupMonths: 1

## Use blended TROPOMI+GOSAT data (true)? Or use operational TROPOMI data (false)?
BlendedTROPOMI: true

## Use observations over water? Set to false to filter out water observations
UseWaterObs: true
>>>>>>> d9df655488eab9901ca902dbcca56e455b1812e0

## Is this a regional inversion? Set to false for global inversion
isRegional: true

## Select two character region ID (for using pre-cropped meteorological fields)
##   Current options are listed below with ([lat],[lon]) bounds:
##     "AF" : Africa ([-37,40], [-20,53])
##     "AS" : Asia ([-11,55],[60,150])
##     "EU" : Europe ([33,61],[-30,70])
##     "ME" : Middle East ([12,50], [-20,70])
##     "NA" : North America ([10,70],[-140,-40])
##     "OC" : Oceania ([-50,5], [110,180])
##     "RU" : Russia ([41,83], [19,180])
##     "SA" : South America ([-59,16], [-88,-31])
##     ""   : Use for global global simulation or custom regions
##   For example, if the region of interest is in Europe ([33,61],[-30,70]), select "EU".
RegionID: "NE"

## Region of interest
##   These lat/lon bounds are only used if CreateAutomaticRectilinearStateVectorFile: true
##   Otherwise lat/lon bounds are determined from StateVectorFile
LonMin: -82.96875
LonMax: -68.59375
LatMin: 37.375
LatMax: 47.875

## ObsPack
## Settings for using ObsPack input
## Warning! This will currently turn off TROPOMI
UseObsPack: true

## Kalman filter options
KalmanMode: false
UpdateFreqDays: 7
NudgeFactor: 0.1
MakePeriodsCSV: true
CustomPeriodsCSV: "/path/to/periods.csv"

## State vector
CreateAutomaticRectilinearStateVectorFile: false
nBufferClusters: 8
BufferDeg: 5
LandThreshold: 0.25
OffshoreEmisThreshold: 0
OptimizeBCs: true
OptimizeOH: false

## Point source datasets
## Used for visualizations and state vector clustering
PointSourceDatasets: ["SRON"]

## Clustering Options
ReducedDimensionStateVector: false
DynamicKFClustering: false
ClusteringMethod: "kmeans"
NumberOfElements: 45
ForcedNativeResolutionElements:
  - [31.5, -104]
EmissionRateFilter: 2500
PlumeCountFilter: 50
<<<<<<< HEAD
GroupByCountry: false

## Custom state vector
StateVectorFile: "/scratch/mloman/gc/imi-v2.2.0/NYStateVector.nc"
=======
GroupByCountry: true

## Custom state vector
StateVectorFile: "/scratch/mloman/gc/imi-v2.0.0/NYStateVector.nc"
>>>>>>> d9df655488eab9901ca902dbcca56e455b1812e0
ShapeFile: "/scratch/mloman/apriori/qgis/Boundaries/tl_2023_us_state/NYS_only.gpkg"

## Inversion
## Notes:
## - PriorError is a relative fraction (e.g. 0.5 = 50%)
## - If lognormal PriorError is the geometric standard deviation (e.g. 2 = factor of 2 uncertainty)
## - PriorErrorOH is a relative fraction (e.g. 0.1 = 10%)
## - PriorErrorBCs is in ppb
## - PriorErrorBufferElements is only used if LognormalErrors is true
LognormalErrors: false
<<<<<<< HEAD
PriorError: [0.5]
PriorErrorBCs: [10.0]
PriorErrorBufferElements: [0.5]
PriorErrorOH: [0.1]
ObsError: [15]
Gamma: [1.0]
PrecomputedJacobian: false

## Grid
##   Options are 0.125x0.15625 (GEOS-FP only), 0.25x0.3125 (GEOS-FP only),
##   0.5x0.625, 2.0x2.5, or 4.0x5.0
=======
PriorError: 0.5
PriorErrorBCs: 10.0
PriorErrorBufferElements: 0.5
PriorErrorOH: 0.1
ObsError: 15
Gamma: 1.0
PrecomputedJacobian: false

## Link existing HEMCO standalone output
## NOTE: must set DoHemcoPriorEmis:true to link
LinkHemco: true
HemcoStandaloneOutputDir: "/scratch/mloman/gc/rundirs/hemco_standalone/3.9.2/hemco_NYregion_geosfp/OutputDir"

## Grid
##   Options are 0.25x0.3125 (GEOSFP only), 0.5x0.625, 2.0x2.5, or 4.0x5.0
>>>>>>> d9df655488eab9901ca902dbcca56e455b1812e0
Res: "0.25x0.3125"

## Meteorology
##   Options are GEOSFP or MERRA2
Met: "GEOSFP"

## Setup modules
##   Turn on/off different steps in setting up the inversion
RunSetup: true
SetupObsPack: true
SetupTemplateRundir: true
SetupSpinupRun: true
<<<<<<< HEAD
SetupJacobianRuns: true
SetupInversion: true
SetupPosteriorRun: true
=======
SetupJacobianRuns: false
SetupInversion: false
SetupPosteriorRun: false
>>>>>>> d9df655488eab9901ca902dbcca56e455b1812e0

## Run modules
##   Turn on/off different steps in performing the inversion
DoHemcoPriorEmis: true
<<<<<<< HEAD
DoSpinup: true
DoJacobian: false
ReDoJacobian: false
DoInversion: false
DoPosterior: false
=======
DoSpinup: false
DoJacobian: false
ReDoJacobian: false
DoInversion: true
DoPosterior: true
>>>>>>> d9df655488eab9901ca902dbcca56e455b1812e0

## IMI preview
##   NOTE: RunSetup must be true to run preview
DoPreview: false
DOFSThreshold: 0

## Slurm general resource settings.
<<<<<<< HEAD
RequestedTime: "0-2:00"
=======
RequestedTime: "0-24:00"
>>>>>>> d9df655488eab9901ca902dbcca56e455b1812e0
SchedulerPartition: "atmos"

## Job specific resource allocation for:
## Jacobian ensemble (array job)
RequestedCPUs: 1
<<<<<<< HEAD
RequestedMemory: 7000
## Compiling GC and running the spin up, prosterior and HEMCO simulations.
GC_CPUs: 16
GC_Memory: 36000
=======
RequestedMemory: 3500
## Compiling GC and running the spin up, prosterior and HEMCO simulations.
GC_CPUs: 12
GC_Memory: 24000
>>>>>>> d9df655488eab9901ca902dbcca56e455b1812e0
## Building jacobian and running inversion.
InversionCPUs: 36
InversionMemory: 124000

## Max number of simultaneous Jacobian runs from the job array (-1: no limit)
MaxSimultaneousRuns: -1

## Number of Jacobians tracers to use for each jacobian simulation
##   Specifying a value = 1 will submit a separate jacobian simulation for each
##   state vector element. Specifying a value > 1 will combine state vector
##   elements into a single jacobian simulation.
<<<<<<< HEAD
NumJacobianTracers: 5
=======
NumJacobianTracers: 2
>>>>>>> d9df655488eab9901ca902dbcca56e455b1812e0

##====================================================================
##
## Advanced Settings (optional)
##
##====================================================================

## These settings are intended for advanced users who wish to:
##   a. modify additional GEOS-Chem options, or
##   b. run the IMI on a local cluster.
## They can be ignored for any standard cloud application of the IMI.

##--------------------------------------------------------------------
## Additional settings for GEOS-Chem simulations
##--------------------------------------------------------------------

## Jacobian settings
## Note PerturbValue is in 1e-8 kg/m2/s. eg specifying 1 means the
## perturbation will be 1e-8 kg/m2/s
## PerturbValueOH is a relative scale factor and PerturbValueBCs is in ppb
PerturbValue: 1.0
PerturbValueOH: 1.1
PerturbValueBCs: 10.0

## Save out hourly diagnostics from GEOS-Chem?
## For use in satellite operators via post-processing -- required for TROPOMI
## inversions
HourlyCH4: true

<<<<<<< HEAD
## IMI validation
## Turn on ObsPack diagnostic in GEOS-Chem?
DoObsPack: true

## Turn on planeflight diagnostic in GEOS-Chem?
## For use in comparing GEOS-Chem against planeflight data. The path
## to those data must be specified in geoschem_config.yml.
=======
## Turn on planeflight diagnostic in GEOS-Chem?
## For use in comparing GEOS-Chem against planeflight data. The path
## to those data must be specified in input.geos.
>>>>>>> d9df655488eab9901ca902dbcca56e455b1812e0
PLANEFLIGHT: false

## Turn on old observation operators in GEOS-Chem?
## These will save out text files comparing GEOS-Chem to observations, but have
## to be manually incorporated into the IMI
GOSAT: false
TCCON: false
AIRS: false

##------------------------------------------------------------------
## Settings for running on local cluster
##------------------------------------------------------------------

## Path for IMI runs and output
<<<<<<< HEAD
OutputPath: "/scratch/mloman/gc/imi-v2.2.0/Output"
=======
OutputPath: "/scratch/pivatt/IMI/Output"
>>>>>>> d9df655488eab9901ca902dbcca56e455b1812e0

## Path to GEOS-Chem input data
DataPath: "/scratch/mloman/data/ExtData"

<<<<<<< HEAD
## Conda environment file
CondaFile: "/software/miniforge3/23.3.1-1/bin/activate base"
CondaEnv: "imi_gc_env"

## Download initial restart file from AWS S3?
##  NOTE: Must have AWS CLI enabled
RestartDownload: true

## Path to initial GEOS-Chem restart file + prefix
##   ("YYYYMMDD_0000z.nc4" will be appended)
RestartFilePrefix: "/scratch/mloman/gc/boundary-conditions-imi/CTCH4_2025_NA/GEOSChem.BoundaryConditions."
=======
## Path to TROPOMI Data
DataPathTROPOMI: "/scratch/mloman/data/tropomi_blended/ch4"

## Path to ObsPack Data
DataPathObsPack: "/scratch/ltmurray_lab/data/input/gc/ObsPack/NYS"

## Conda environment file
## See envs/README to create the Conda environment specified below
CondaEnv: "imi_env"
CondaFile: "/software/miniforge3/23.3.1-1/bin/activate base"

## GEOS-Chem environment file (with fortran compiler, netcdf libraries, etc.)
##   NOTE: Copy your own file in the envs/ directory within the IMI
GEOSChemEnv: "envs/Rochester-Bluehive/GCClassic.14.4_gnu.env"

## Download initial restart file from AWS S3?
##   NOTE: Must have AWS CLI enabled
RestartDownload: false

## Path to initial GEOS-Chem restart file + prefix
##   ("YYYYMMDD_0000z.nc4" will be appended)
RestartFilePrefix: "/scratch/mloman/gc/boundary-conditions-imi/v2023-06/GEOSChem.BoundaryConditions."
>>>>>>> d9df655488eab9901ca902dbcca56e455b1812e0

## Path to GEOS-Chem boundary condition files (for regional simulations)
## BCversion will be appended to the end of this path. ${BCpath}/${BCversion}
BCpath: "/scratch/mloman/gc/boundary-conditions-imi"
<<<<<<< HEAD
BCversion: "CTCH4_2025_NA"

## Options to download missing GEOS-Chem input data from AWS S3
=======
BCversion: "v2023-06"

## Options to download missing GEOS-Chem input data from AWS S3
##   NOTE: Must have AWS CLI enabled
>>>>>>> d9df655488eab9901ca902dbcca56e455b1812e0
HemcoPriorEmisDryRun: false
SpinupDryrun: false
ProductionDryRun: false
PosteriorDryRun: false
BCdryrun: false
